spring:
  application:
    name: ai-generation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai-generation
    username: root
    password: 20050113
  profiles:
    active: local

server:
  port: 8080
  servlet:
    context-path: /api
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: org.example.aigeneration.controller
knife4j:
  enable: true
  setting:
    language: zh_cn


